#!/sbin/bb/busybox ash
# osm0sis @ xda-developers

bb=/sbin/bb/busybox;
cache=/dev/block/platform/*/*/by-name/cache;
data=/dev/block/platform/*/*/by-name/userdata;
system=/dev/block/platform/*/*/by-name/system;
device=tuna;

# check partition filesystem
getfs() { $bb blkid $1 | $bb cut -d\" -f4; }

case $1 in
  mkfstab)
    # copy in base if using included Minimal fstab - not required with AnyKernel2
    if [ "$($bb grep Minimal /fstab.$device)" ]; then
      # use base matching cache fstype to accomodate encryption users - no effect otherwise
      fsbase=`getfs $cache`;
      $bb cp -f /fstab-$fsbase.$device /fstab.$device;
    fi;
    # swap out entries for filesystems as detected
    for i in $system $cache $data; do
      fstype=`getfs $i`;
      fsentry=`$bb grep $i /fstab-$fstype.$device`;
      if [ "$fsentry" ]; then
        $bb sed -i "s|^$i.*|$fsentry|" /fstab.$device;
      fi;
    done;
    $bb rm -f /fstab-*;
  ;;
  setprops)
    # set filesystem type properties for external use - system mount (toolbox) required
    setprop ro.fs.cache `getfs $cache`;
    setprop ro.fs.data `getfs $data`;
    setprop ro.fs.system `getfs $system`;
  ;;
esac;

